### ISSUE TITLE
Why is it not displayed by the list of variables?

### ISSUE THREAD

**Issue by hokut-o** [SC5/sc5-styleguide#1017]
_test.scss

``` css
@import 'styles/variables';

// Button
//
// primary button
//
// Markup:
// <p class="btn primary">button</p>
//
// Styleguide 1.0.0
.btn {
  border-radius: 3px;
  display: flex;
  justify-content: center;
  align-items: center;
  &.primary {
    background: $color__grey;
    color: #fff;
    width: 100px;
    height: 44px;
  }
}
```

_variables.scss

```
$color__grey:#212121;
```

Why is it not displayed by the list of variables?
![image](https://cloud.githubusercontent.com/assets/10446161/19512120/5306b52a-9625-11e6-8c74-81205a6fbbc6.png)
