### ISSUE TITLE
:not pseudo selector issue

### ISSUE THREAD

**Issue by Janpot** [SC5/sc5-styleguide#266]
Consider following case:

``` scss
/*
test

Markup:
<div">
  <div class="item">1</div>
  <div class="item">2</div>
  <div class="item">3</div>
</div

Styleguide 0
*/

.item {
  background: blue;
}

.item:not(:first-child) {
  background: red;
}
```

This shows all items in red while the first one is supposed to be blue. This seems to only happen when a pseudoselector is used in the `:not` selector. With a normal class it works. It seems the translated `.pseudo-class-first-child` is not added to the classlist.

It also seems to fail for `:last-child`, `:first-of-type` and `:last-of-type`

**Edit**
Ok, now I see what happens here. It seems there are two possible solutions IMO:
1. Don't generate `.pseudo-class-...` rules for `:first-child`, `last-child`,... when they appear in the `:not()` clause
2. Add pseudoclasses to the bound html through a directive, adding `angular.element(element[0].querySelectorAll(':first-child')).addClass('pseudo-class-first-child');` in the `dynamicCompile` directive's watch function seemed to solve this particular case for me. Obviously you'd want a more robust solution that covers all cases and doesn't pollute the `dynamicCompile` directive.
