### ISSUE TITLE
My list styles mess up the menu and modifiers lists

### ISSUE THREAD

**Issue by Janpot** [SC5/sc5-styleguide#268]
I have following styles defined:

``` scss

ul {
  padding-left: 0;

  li {
    list-style: none;
  }

  li:before {
    padding-right: 30px;
    content: "•";
    font-size: 13px;
    color: #888888;
  }

  ul &, ol & {
    margin: 18px 0 18px 30px;
    li:before {
      content: "◦";
    }
  }
}
```

This is what that does to the menu and modifier lists

![screen shot 2014-11-25 at 15 36 10](https://cloud.githubusercontent.com/assets/2109932/5184572/d666b6f8-74b8-11e4-8080-114919714d22.png)
![screen shot 2014-11-25 at 15 36 01](https://cloud.githubusercontent.com/assets/2109932/5184573/d7915916-74b8-11e4-986b-c79835c2c84d.png)
