### ISSUE TITLE
Using less variable interpolation causes Gonzales error

### ISSUE THREAD

**Issue by kr3l** [SC5/sc5-styleguide#577]
Hi, 

I have some less styles using variable interpolation, as shown below:

```less
.funnel-based-color(@property: border-left-color, @funnel-attribute: data-annotation-funnel) {
  &[@{funnel-attribute}=TranscriptAnnotation] {
    border-color: red;
  }
}
```

When trying to generate the styleguide (v0.3.11), it says

> Parsing error: Please check the validity of the block starting from line #undefined      
>                                                                      
> Gonzales PE version: 3.0.0-12                                                            

Note: I tried surrounding the code with 

```
//styleguide:ignore:start
...
//styleguide:ignore:end
```

to at least be able to generate the Styleguide without the styles causing the parse error, but the same error occurs.
