### ISSUE TITLE
Styles not applied to elements

### ISSUE THREAD

**Issue by ciarand** [SC5/sc5-styleguide#613]
![image](https://cloud.githubusercontent.com/assets/2149341/7546415/435a443c-f592-11e4-9234-7f57b02cee70.png)

No styles are being applied to the elements within the shadow dom, as shown in the screenshot. The error in the console is:

>The specified value '{{color.value}}' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers

This is the raw scss file I'm using:

```scss
$default-action-color: #1e90ff;
$action-color-change: 20;
$primary-action-color: #2e8b57;
$secondary-color: #ff4500;

// Buttons
//
// Button styles used in the styleguide
//
// default - Default button
// .primary - Primary button
// :disabled - Disabled button
//
// markup:
// <button class="sg {$modifiers}">Button text</button>
//
// Styleguide 1.0

button.sg {
    display: inline;

    margin-right: 8px;
    padding: 8px;

    cursor: pointer;

    color: #ffffff;
    border-radius: 5px;
    background-color: $default-action-color;

    &:hover {
        background-color: lighten($default-action-color, $action-color-change);
    }
    &:active {
        background-color: darken($default-action-color, $action-color-change);
    }

    &.primary {
        color: #ffffff;
        background-color: $primary-action-color;
        &:hover {
            background-color: lighten($primary-action-color, $action-color-change);
        }
        &:active {
            background-color: darken($primary-action-color, $action-color-change);
        }
    }

    &:disabled {
        cursor: default;

        color: #999999;
        background-color: $secondary-color;
    }
}
```

Here's my Gulpfile:

```js
var gulp = require('gulp'),
    sass = require('gulp-sass'),
    styleguide = require('sc5-styleguide'),
    source = 'app/styles/*.scss',
    outputPath = 'styleguide';

gulp.task('styleguide:generate', function() {
    return gulp.src(source)
        .pipe(styleguide.generate({
            title: 'my cool styleguide',
            server: true,
            rootPath: outputPath,
            overviewPath: 'README.md'
        }))
        .pipe(gulp.dest(outputPath));
});

gulp.task('styleguide:applystyles', function() {
    return gulp.src('')
        .pipe(sass({
            errLogToConsole: true,
            includePaths: ["bower_components", "node_modules"]
        }))
        .pipe(styleguide.applyStyles())
        .pipe(gulp.dest(outputPath));
});

gulp.task('styleguide', ['styleguide:generate', 'styleguide:applystyles']);

gulp.task('watch', ['styleguide'], function() {
    // Start watching changes and update styleguide whenever changes are detected
    gulp.watch(source, ['styleguide']);
});
```

What can I do to help fix this problem?
