### ISSUE TITLE
Gonzales PE LESS extend feature not supported

### ISSUE THREAD

**Issue by ayjee** [SC5/sc5-styleguide#726]
gonzales pe is failing when attempting to use LESS' extend feature.
I am attempting to use it via the syntax example on the less documentation page.  
gonzales pe has a closed issue on the same subject but it does not look as though this fix has made its way to production.

```css
.animal {
  background-color: black;
  color: white;
}
.bear {
  &:extend(.animal);
  background-color: brown;
}
```
