### ISSUE TITLE
sg-insert doesn't work inside of sg-wrapper

### ISSUE THREAD

**Issue by ian-pvd** [SC5/sc5-styleguide#748]
Trying to use `<sg-insert>` tags inside of a `sg-wrapper` block results in just the section reference numbers being displayed and not the referenced markup. (Using the same  `<sg-insert>` tags inside of the `markup` block is working without issue.)

Use case: I'm trying to show how new markup with `{$modifiers}` relates to an existing component.

**Comment by kraftner** [comment]
:+1: 

Another use case: Putting a header on top of a couple of sub-components that need a common wrapper the header can't be in.

**Comment by g12n** [comment]
I tried the same thing. Though i guess it's less a bug then a feature. 

I have put together a quick Use Case for testing: 

### 1. Definition of a common Wrapper for a modal

```scss
// Modal Wrapper
//
// markup:
// <div class="modal">
//  <header class="modal-header">
//    modal title 
//    <span class="close></span>
//  </header>
//   <sg-wrapper-content/>
// </div>
//
// Styleguide 1.2

.modal{
  background:#fff;
  box-shadow: 0 0 10px rgba(0,0,0,0.5);
  padding: 0; 
  header{
    background: #444;
    color:#fff
  }
}
```

### 2. Wrapping a different section into the modal

```scss
// Registration Form
//
// markup:
// <form>
// <span> ... </span>
// </form>
//
// sg-wrapper:
// <sg-insert>1.2</sg-insert>
//
// Styleguide 4.4.1
```

This would allow to Quickly test changes in the Markup and Style of widely used elements.
