### ISSUE TITLE
Show KSS comments errors

### ISSUE THREAD

**Issue by DimitryDushkin** [SC5/sc5-styleguide#765]
I had wrong KSS comment text, but running `gulp styleguide:generate` just silently failed:
```
[12:15:34] Using gulpfile ./gulpfile.js
[12:15:34] Starting 'styleguide:generate'.. 
```

I spent a lot of time figuring out, that the problem was in wrong KSS comment format. So it will be great sc5-styleguide to show such errors.

**Comment by varya** [comment]
Could you provide your source code (CSS) or link to the repo? Hard to say what's wrong without being able to run ourselves.

**Comment by DimitryDushkin** [comment]
This code leads to problem:
```scss
// _btn.scss

/*
A button with a white border 
:hover             - Subtle hover shadow.
markup:
<a class="{$modifiers}">press me</a>
Styleguide 1.0.0.
*/

.white_border_btn{
  width: 100%;
  border: 4px solid #ffffff;
  text-transform: uppercase;
  color: #ffffff;
  min-height: 50px;
  display: block;
  line-height: 50px;
  margin-bottom: 20px;
  text-align: center;
  font-weight: bold;
  &:hover{
    text-decoration: none;
    box-shadow: inset 0 0 0 1px #FAFAFA;
  }
}
```

Yes, it's full of errors, sorry. I've fixed it later.

Gulp config is mostly "default":
```js
gulp.task('styleguide:generate', function() {
  return gulp
  .src(sourcePath)
  .pipe(styleguide.generate({
    title: 'Some Styleguide',
    server: true,
    rootPath: outputPath,
    overviewPath: 'README.md'
  }))
  .pipe(gulp.dest(outputPath));
});
```
