### ISSUE TITLE
Cascaded styles are not applied in encapsulation mode

### ISSUE THREAD

**Issue by karlhorky** [SC5/sc5-styleguide#769]
We set the `font-family` on our elements through cascading rules on the `body` element:

```css
body {
  font-family: 'Whitney SSm A', 'Whitney SSm B', sans-serif;
}
```

By default these styles are not showing up in our components when they are encapsulated in a Shadow DOM.

The cascading styles appear if I set `disableEncapsulation` to true.

Thanks for this great project by the way!
