### ISSUE TITLE
Custom App UI styles + variables

### ISSUE THREAD

**Issue by onlyskyguy** [SC5/sc5-styleguide#816]
What's the best way to modify the UI variables without editing the sass files in the node_modules directory for sc5-styleguide? 

I'd like to have have project specific overrides to the sc5-styleguide UI and maintain that code inside my sass src directory.

Thanks for any help!

**Comment by hannu** [comment]
You can use `customColors` option specify the file that contains custom variables. See https://github.com/SC5/sc5-styleguide#user-content-option-customColors

**Comment by onlyskyguy** [comment]
Perfect! Thanks!!

**Comment by shanecarmody** [comment]
Is there any further documentation on this? I’ve created a file called `_styleguide_custom_variables.css` in the root of my project. The file looks like this:

```css
@define-mixin styleguide_custom_styles {
  :root {
  --primary-color: gold;
  --secondary-color: blue;
  --tertiary-color: red;
  }
}
```

So I’m overwriting the variables defined by the styleguide by default. I then reference this CSS file in my `gulpfile.js` using the `customColors` option. However, when I run the `styleguide` task and reload the page, it doesn’t affect the colours of the UI. Am I declaring the variables incorrectly?
