### ISSUE TITLE
Feature Request: Using Inserted markup as a wrapper

### ISSUE THREAD

**Issue by g12n** [SC5/sc5-styleguide#822]
It would be nice to use a previously defines element as a wrapper.
This would be useful, if you have a common markup for an element, but use it in many different contexts, like dialogs. 

First i thought this was related to https://github.com/SC5/sc5-styleguide/issues/748

But I guess it's a completely new concept. In the following exampe i use a comment section calles `sg-wrap-into:` and a `<sg-wrapper>`-tag as placeholders for this possible solution. 
### 1. Definition of a common Wrapper for a modal

``` scss
// Modal Wrapper
//
// markup:
// <div class="modal">
//  <header class="modal-header">
//    modal title 
//    <span class="close></span>
//  </header>
//   <sg-wrapper-content/>
// </div>
//
// Styleguide 1.2

.modal{
  background:#fff;
  box-shadow: 0 0 10px rgba(0,0,0,0.5);
  padding: 0; 
  header{
    background: #444;
    color:#fff
  }
}
```
### 2. Wrapping a different section into the modal

``` scss
// Registration Form
//
// markup:
// <form>
// <span> ... </span>
// </form>
//
// sg-wrap-into:
// <sg-wrapper>1.2</sg-wrapper>
//
// Styleguide 4.4.1
```

This would allow to Quickly test changes in the Markup and Style of widely used elements.
