### ISSUE TITLE
Issues Generating Style Guide

### ISSUE THREAD

**Issue by devonatdomandtom** [SC5/sc5-styleguide#839]
I don't see any style guide being generated when I navigate to localhost:3000.

Gruntfile
```javascript
 gulp: {
      'styleguide-generate': function() {
          var outputPath = 'styleguide';
          return gulp.src(['<%= config.app %>/styles/main.scss'])
              .pipe(styleguide.generate({
                  title: 'CNN Pol Quiz Styleguide',
                  server: true,
                  rootPath: outputPath,
                  overviewPath: 'README.md'
              }))
              .pipe(gulp.dest(outputPath));
      },
      'styleguide-applystyles': function() {
          gulp.src('<%= config.app %>/styles/main.scss')
              .pipe(styleguide.applyStyles())
              .pipe(gulp.dest('styleguide'));
      }
    },
```
Gruntfile watch sass attribute

```javascript
sass: {
        files: ['<%= config.app %>/styles/{,*/}*.{scss,sass}'],
        tasks: ['sass', 'postcss', 'gulp:styleguide-generate', 'gulp:styleguide-applystyles']
      },
```

Gruntfile serve task
```javascript
grunt.registerTask('serve', 'start the server and preview your app', function (target) {

    if (target === 'dist') {
      return grunt.task.run(['build', 'browserSync:dist']);
    }

    grunt.task.run([
        'clean:server',
        'wiredep',
        'concurrent:server',
        'postcss',
        'browserSync:livereload',
        'gulp:styleguide-generate',
        'gulp:styleguide-applystyles',
        'watch'
    ]);
  });
```
main.scss file
```scss
// Headings
//
// These are our headings
//
// markup:
// <h1 class="sg">Heading 1</h1>
// <p class="sg">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque massa ipsum, tincidunt vel convallis in, suscipit et risus. Morbi erat dolor, mattis at dignissim sed, feugiat sed lorem.
// <h2 class="sg">Heading 2</h2>
// <p class="sg">Mauris feugiat suscipit turpis, ut rhoncus lectus finibus sed. Etiam suscipit consectetur eros vitae venenatis.</p>
// <h3 class="sg">Heading 3</h3>
// <p class="sg">Ut leo ipsum, tincidunt vel mauris eget, convallis egestas justo. Nunc ligula neque, porta ac lorem id, ultrices dapibus dolor.</p>
// <h4 class="sg">Heading 4</h4>
// <p class="sg"> Phasellus interdum massa ante, ac placerat felis ultricies at. Fusce vulputate, odio sed convallis laoreet, tortor orci venenatis massa, a placerat ligula nisl vitae felis. In pellentesque ornare eleifend. Suspendisse potenti. Quisque eget mauris enim.</p>
// <h5 class="sg">Heading 5</h5>
//
// Styleguide 1.0

h1.sg,
h2.sg,
h3.sg,
h4.sg,
h5.sg {
  font-weight: normal;
  font-style: normal;
  line-height: 1.2;
  margin: 1.414em 0 .5em;
  color: #444;
}

h1.sg {
  font-size: 3.157em;

  margin-top: .5em;
}

h2.sg {
  font-size: 2.369em;
}

h3.sg {
  font-size: 1.777em;
}

h4.sg {
  font-size: 1.333em;
}

h4.sg,
h5.sg {
  font-weight: 500;
}
```
