### ISSUE TITLE
SASS variables and modifiers returns the function call itself instead of the result

### ISSUE THREAD

**Issue by qtgye** [SC5/sc5-styleguide#928]
Consider this:

```scss
// Color Variables
// 
// The colors used in the entire site
// 
// $main-color - Main Color
// $highlight-color - Highlight color
// $bg-color - Default background color
// 
// markup:
// <div style="background: {$modifiers};" class="styleguide-color">{$modifiers}</div>
// 
// Styleguide 5

$palettes: (
	yellow: (
		base:    #f3ef31
	),
	gray: (
		base:    #999999,
        dark:    #242323
	),
	black: (
		base:    #000000
	),
	white: (
		base:    #fff
	),
	light-blue: (
	  	base:	 #deeae6
	)
);

$main-color: palette(black);
$highlight-color: palette(yellow);
$bg-color: palette(white);
```

On the styleguide page It should generate the hex values in place of `{$modifiers}`, instead it generates the function `palette(black)` itself as a string.
```html
<div style="background: palette(black)" class="styleguide-color">palette(black)</div>
```
