### ISSUE TITLE
How to add the JS of my Angular Module to SC5

### ISSUE THREAD

**Issue by DanielaValero** [SC5/sc5-styleguide#979]
Hello,

I have been trying to figure out how to add the JS of my component to the styleguide, however did not have success so far. At the moment I get this error:

"[ng:areq] Argument 'HelloWorldController' is not a function, got undefined"

This is my config:

gulp task
```js
    .pipe(sc5.generate({
      title: 'Bosch living syleguide',
      server: false,
      appRoot: '/styleguide',
      readOnly: true,

      disableEncapsulation: true,
      sideNav: true,
      extraHead: `<link rel="shortcut icon" href="/favicon.png">
                  <link rel="stylesheet" type="text/css" href="/styleguide/styleguide-custom.css">`,
      overviewPath: 'README.md',
      afterBody: '<script src="/scripts/main.js"></script>',
      customColors: `${paths.styleguideSrc}/styles/_styleguide_variables.scss`,
    }))
```

component scss
```scss
// JS component (Sample)
//
// Markup:
// <a ng-controller="HelloWorldController as ctrl"
// ng-href="[[ctrl.href]]" target="[[ctrl.target]]">
// Directive not working yet
// </a>
//
// Styleguide 2.0


a.helloWorld-primary {
  color: $helloWorld-new-color;
}
```

I also tried adding my JS to the `extraHead` but no success, same error. 
Also tried not adding the JS to the sc5 generate task but using an angular-directive, to avoid copy and paste of the markup, but also got the same error.

```scss
// JS component (Sample)
//
// Markup:
// <a ng-controller="HelloWorldController as ctrl"
// ng-href="[[ctrl.href]]" target="[[ctrl.target]]">
// Directive not working yet
// </a>
//
// Styleguide 2.0
// sg-angular-directive:
// name: helloWorld
// template: components/molecules/helloWorld/helloWorld.html
// file: /scripts/main.js


a.helloWorld-primary {
  color: $helloWorld-new-color;
}
```

I have searched in the issues, googled it, but after lots of hours spent on this I really still don't get it. I wondered if you could help me to find out what is the config I am missing?

Thanks in advance
