### ISSUE TITLE
Custom UI colors not working

### ISSUE THREAD

**Issue by shanecarmody** [SC5/sc5-styleguide#982]
Is there any further documentation on this? I’ve created a file called `_styleguide_custom_variables.css` in the root of my project. The file looks like this:

```css
@define-mixin styleguide_custom_styles {
  :root {
  --primary-color: gold;
  --secondary-color: blue;
  --tertiary-color: red;
  }
}
```

So I’m overwriting the variables defined by the styleguide by default. I then reference this CSS file in my `gulpfile.js` using the `customColors` option. However, when I run the `styleguide` task and reload the page, it doesn’t affect the colours of the UI. Am I declaring the variables incorrectly?
